trigger:
  - none

pool:
  vmImage: ubuntu-latest

variables:
  TF_WORKING_DIR: "$(System.DefaultWorkingDirectory)/infra"
  AZURE_SERVICE_CONNECTION: "Bootstrap-terraform"

parameters:
  - name: deployEnvironments
    type: object
    default:
      - dev
      - prod

# Deploy to each specified environment
stages:
  - ${{ each environment in parameters.deployEnvironments }}:
      - template: template/deployment-template.yml
        parameters:
          environment: ${{ environment }}
          approverEmail: "gamertech996@gmail.com"
          components:
            - core-infra
            # Uncomment to add more components:
            # - service
            # - storage
